# Generated by Django 4.0.3 on 2022-04-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
